name: hero_button
description: A beautiful button library for flutter, made easy to use properties which can't used in default button, user can apply color, icon, padding easily which using extra code.
version: 2.0.0
homepage: https://github.com/rohit-chouhan
repository: https://github.com/rohit-chouhan/hero_button

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: "Screenshot Logo | Copyright by pngtree.com"
    path: logo-hero-button.png

topics:
  - button
  - hero-button
  - custom-button
  - animation-button
  - loading-button
